version: "3"
services:
    api:
        image: bala876/fastapi 
        depends_on:
            - postgres
        ports:
            - 80:8000
        # command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
        # env_file: ./.env
        environment:
            - DATABASE_HOSTNAME=${DATABASE_HOSTNAME}
            - DATABASE_PORT=${DATABASE_PORT}
            - DATABASE_USERNAME=${DATABASE_USERNAME}
            - DATABASE_PASSWORD=${DATABASE_PASSWORD}
            - DATABASE_NAME=${DATABASE_NAME}
            - SECRET_KEY_FASTAPI=${SECRET_KEY_FASTAPI}
            - ALGORITHM=${ALGORITHM}
            - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
    postgres:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        volumes:
            - postgres-db:/var/lib/postgresql/data
volumes:
    postgres-db:
