version: "3"
services:
    api:
        build: .
        depends_on:
            - postgres
        ports:
            - 8000:8000
        volumes:
            - ./:/usr/src/app:ro
        command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
        # env_file: ./.env
        environment:
            - DATABASE_HOSTNAME=postgres
            - DATABASE_PORT=5432
            - DATABASE_USERNAME=postgres
            - DATABASE_PASSWORD=postgres
            - DATABASE_NAME=fastapi
            - SECRET_KEY_FASTAPI=feead84a0e7534a88155631e682b0df77bd491f8423c851046aaa678bc362c99
            - ALGORITHM=HS256
            - ACCESS_TOKEN_EXPIRE_MINUTES=300
    postgres:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=fastapi
        volumes:
            - postgres-db:/var/lib/postgresql/data
volumes:
    postgres-db:
